### ISSUE TITLE
open `log.txt` instead of `error_log.txt` by default

### ISSUE THREAD

**Issue by microlith57** [EverestAPI/Everest#613] opened 2023-04-17 11:30 UTC
### I am planning on implementing this myself

Yes

### Describe your request

a lot of people see the message to "drag and drop your log.txt into #modding_help" in the error log file that opens on crash, and instead do the more obvious thing of sending the file that opened (which is often less useful than the full log).
this would be easily fixed (for some exceptions at least, probably `RunWithLogging` will get most of them) by simply adding the banner with message to log.txt, perhaps along with the exception raised, and opening that instead.

also probably the error_log message should be changed to clarify that it's talking about a separate file, and explain where to find it

**Comment by Kalobi** [comment] 2023-04-17 16:35
Duplicate of #432

**Closed as completed by Kalobi** 2023-04-17 16:35 UTC
Labels: duplicate, enhancement
