### ISSUE TITLE
Game crash when loading save into a non-existent room

### ISSUE THREAD

**Issue by DemoJameson** [EverestAPI/Everest#626] opened 2023-05-08 03:29 UTC
### My mods and Everest install are up to date

Yes

### I have recreated the bug with only Everest OR a minimum number of mods enabled

Yes

### Describe the bug

Game crash when loading save into a non-existent room, since session.LevelData is null
Note this crash is also happens withou any mod is enabled
https://discord.com/channels/403698615446536203/1104654739431510096/1104654739431510096

### Steps to reproduce

1. Enter any level then `Save & Quit`
2. Change the name of the room you were in when you saved and reload the map
3. Load into the save

### Expected behavior

Show postcard with error message

### Operating System

Windows 11

### Everest Version

3971

**Comment by mayromr** [comment] 2023-06-11 08:54
After debugging this for a bit, I found out that this line of code causes the issue:
https://github.com/EverestAPI/Everest/blob/fdc6ddbf3f897799cff2a5e3c0ac72514621d64e/Celeste.Mod.mm/Patches/Level.cs#L228

After failing to load the level, we try to log `Session.LevelData.Name` but `Session.LevelData` is null, so we get `System.NullReferenceException`.

I am not on my windows machine so I can't dig into why is `Session.LevelData` null, I'll look into it later on today.

For now an easy fix would be to remove the log call temporary, the logic to display the postcard is already present.

**Comment by mayromr** [comment] 2023-06-11 12:23
Might be duplicate of #583.

**Closed as completed** 2023-08-01 09:00 UTC
Labels: bug
