### ISSUE TITLE
Missing libMonoPosixHelper.dylib on Mac

### ISSUE THREAD

**Issue by tbodt** [EverestAPI/Everest#34] opened 2019-02-04 04:42 UTC
```
Ver 1.2.6.1 [Everest: 797-azure-5f3fa]
02/03/2019 20:32:31
System.DllNotFoundException: libMonoPosixHelper.dylib
  at (wrapper managed-to-native) System.IO.Compression.DeflateStreamNative.CreateZStream(System.IO.Compression.CompressionMode,bool,System.IO.Compression.DeflateStreamNative/UnmanagedReadOrWrite,intptr)
  at System.IO.Compression.DeflateStreamNative.Create (System.IO.Stream compressedStream, System.IO.Compression.CompressionMode mode, System.Boolean gzip) [0x0004a] in <4deb318bb3254cab91ca66698a056198>:0 
  at System.IO.Compression.DeflateStream..ctor (System.IO.Stream compressedStream, System.IO.Compression.CompressionMode mode, System.Boolean leaveOpen, System.Boolean gzip) [0x0002d] in <4deb318bb3254cab91ca66698a056198>:0 
  at System.IO.Compression.DeflateStream..ctor (System.IO.Stream stream, System.IO.Compression.CompressionLevel compressionLevel, System.Boolean leaveOpen, System.Boolean gzip) [0x00000] in <4deb318bb3254cab91ca66698a056198>:0 
  at System.IO.Compression.DeflateStream..ctor (System.IO.Stream stream, System.IO.Compression.CompressionLevel compressionLevel, System.Boolean leaveOpen) [0x00000] in <4deb318bb3254cab91ca66698a056198>:0 
  at (wrapper remoting-invoke-with-check) System.IO.Compression.DeflateStream..ctor(System.IO.Stream,System.IO.Compression.CompressionLevel,bool)
  at Jdenticon.IO.ZlibStream..ctor (System.IO.Stream stream) [0x00047] in <ab564dc515b94c289a2d06cfad69bf6e>:0 
  at (wrapper remoting-invoke-with-check) Jdenticon.IO.ZlibStream..ctor(System.IO.Stream)
  at Jdenticon.Drawing.Png.PngEncoder.WriteImageData () [0x00011] in <ab564dc515b94c289a2d06cfad69bf6e>:0 
  at Jdenticon.Drawing.Png.PngEncoder.Save (System.IO.Stream output) [0x00047] in <ab564dc515b94c289a2d06cfad69bf6e>:0 
  at Jdenticon.Drawing.Bitmap.SaveAsPng (System.IO.Stream stream) [0x0002b] in <ab564dc515b94c289a2d06cfad69bf6e>:0 
  at Jdenticon.Rendering.PngRenderer.SavePng (System.IO.Stream stream) [0x00000] in <ab564dc515b94c289a2d06cfad69bf6e>:0 
  at Jdenticon.PngExtensions.GeneratePng (Jdenticon.Identicon icon) [0x00027] in <ab564dc515b94c289a2d06cfad69bf6e>:0 
  at Jdenticon.PngExtensions.SaveAsPng (Jdenticon.Identicon icon) [0x00000] in <ab564dc515b94c289a2d06cfad69bf6e>:0 
  at Celeste.AreaComplete.Begin () [0x0004a] in <e6396995e64e4637a8dd70ee94d7253d>:0 
  at (wrapper dynamic-method) Monocle.Engine.DMD<Monocle.Engine::Update>(Monocle.Engine,Microsoft.Xna.Framework.GameTime)
  at TAS.EverestInterop.CelesteTASModule.Engine_Update (On.Monocle.Engine+orig_Update orig, Monocle.Engine self, Microsoft.Xna.Framework.GameTime gameTime) [0x00064] in <1d07fbc9f1a947228cc8ba943be88cd1>:0 
  at (wrapper dynamic-method) Monocle.Engine.Hook<Monocle.Engine::Update>?-1737187478(Monocle.Engine,Microsoft.Xna.Framework.GameTime)
  at Celeste.Celeste.Update (Microsoft.Xna.Framework.GameTime gameTime) [0x00030] in <e6396995e64e4637a8dd70ee94d7253d>:0 
  at Microsoft.Xna.Framework.Game.Tick () [0x000ef] in <d8a8e8a23bae436f88420b87ce0d373a>:0 
  at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop (Microsoft.Xna.Framework.Game game) [0x005ed] in <d8a8e8a23bae436f88420b87ce0d373a>:0 
  at Microsoft.Xna.Framework.Game.Run () [0x0002c] in <d8a8e8a23bae436f88420b87ce0d373a>:0 
  at Monocle.Engine.RunWithLogging () [0x00000] in <e6396995e64e4637a8dd70ee94d7253d>:0 
```

This happens when you finish a level, seems to be crashing in the process of adding the version number to the completion screen. I fixed it for myself by copying libMonoPosixHelper.dylib from another Mono installation.

**Comment by 0x0ade** [comment] 2019-02-05 09:37
If possible, can you please share your copy of libMonoPosixHelper.dylib? I'll then include it in Everest like it already includes some missing libraries for Windows FNA.

Unfortunately I don't own a Mac, and those who tried to use libMonoPosixHelper.dylib from another installation didn't have as much success in the past.

**Comment by tbodt** [comment] 2019-02-05 18:21
Pretty sure the problem happened because I installed mono through homebrew instead of off the website. You can find libMonoPosixHelper.dylib if you extract the .pkg download from the mono website, I tried that version and it works fine.

**Comment by 0x0ade** [comment] 2019-02-05 19:00
That's good to know, thanks!

The issue is because Celeste ships with its own copy of mono (specifically, MonoKickstart), which lacks that specific library.

I'll close the issue once I can get another macOS user (maybe on the Discord server) to confirm that the next Everest build works for them.

**Comment by cdparks** [comment] 2019-04-12 14:10
I had the same issue, and copying `libMonoPosixHelper.dylib` seemed to stop the crashing.

I'm using this version of mono downloaded from the website:

```console
$ mono --version
Mono JIT compiler version 5.16.1.0 (2018-06/a76b50e5faa Thu Mar 14 15:41:21 PDT 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-release_60/0b3cb8ac12c)
	GC:            sgen (concurrent by default)
```

I copied the library like so:

```console
$ cp /Library/Frameworks/Mono.framework/Libraries/libMonoPosixHelper.dylib \
  ~/Library/Application\ Support/Steam/steamapps/common/Celeste/Celeste.app/Contents/MacOS/osx/
```

**Comment by 0x0ade** [comment] 2019-09-03 15:01
![image](https://user-images.githubusercontent.com/1200380/64184822-59ce6880-ce6c-11e9-9068-f3ea58f86c4e.png)

A macOS user just confirmed that it's now working properly. Thanks to everyone involved in this issue, and sorry for the lack of any updates for so long.

**Comment by gabtoubl** [comment] 2020-03-12 10:09
Hey, I got a similar issue, but on Linux this time (Ubuntu 18.04):
```
Celeste Error Log
==========================================

Ver 1.3.1.2 [Everest: 1441-azure-43ade]
03/12/2020 11:06:18
System.DllNotFoundException: libMonoPosixHelper.so
  at (wrapper managed-to-native) System.IO.Compression.DeflateStreamNative.CreateZStream(System.IO.Compression.CompressionMode,bool,System.IO.Compression.DeflateStreamNative/UnmanagedReadOrWrite,intptr)
  at System.IO.Compression.DeflateStreamNative.Create (System.IO.Stream compressedStream, System.IO.Compression.CompressionMode mode, System.Boolean gzip) [0x0004a] in <4deb318bb3254cab91ca66698a056198>:0 
  at System.IO.Compression.DeflateStream..ctor (System.IO.Stream compressedStream, System.IO.Compression.CompressionMode mode, System.Boolean leaveOpen, System.Boolean gzip) [0x0002d] in <4deb318bb3254cab91ca66698a056198>:0 
  at System.IO.Compression.DeflateStream..ctor (System.IO.Stream stream, System.IO.Compression.CompressionLevel compressionLevel, System.Boolean leaveOpen, System.Boolean gzip) [0x00000] in <4deb318bb3254cab91ca66698a056198>:0 
  at System.IO.Compression.DeflateStream..ctor (System.IO.Stream stream, System.IO.Compression.CompressionLevel compressionLevel, System.Boolean leaveOpen) [0x00000] in <4deb318bb3254cab91ca66698a056198>:0 
  at (wrapper remoting-invoke-with-check) System.IO.Compression.DeflateStream..ctor(System.IO.Stream,System.IO.Compression.CompressionLevel,bool)
  at Jdenticon.IO.ZlibStream..ctor (System.IO.Stream stream) [0x00047] in <ab564dc515b94c289a2d06cfad69bf6e>:0 
  at (wrapper remoting-invoke-with-check) Jdenticon.IO.ZlibStream..ctor(System.IO.Stream)
  at Jdenticon.Drawing.Png.PngEncoder.WriteImageData () [0x00011] in <ab564dc515b94c289a2d06cfad69bf6e>:0 
  at Jdenticon.Drawing.Png.PngEncoder.Save (System.IO.Stream output) [0x00047] in <ab564dc515b94c289a2d06cfad69bf6e>:0 
  at Jdenticon.Drawing.Bitmap.SaveAsPng (System.IO.Stream stream) [0x0002b] in <ab564dc515b94c289a2d06cfad69bf6e>:0 
  at Jdenticon.Rendering.PngRenderer.SavePng (System.IO.Stream stream) [0x00000] in <ab564dc515b94c289a2d06cfad69bf6e>:0 
  at Jdenticon.PngExtensions.GeneratePng (Jdenticon.Identicon icon) [0x00027] in <ab564dc515b94c289a2d06cfad69bf6e>:0 
  at Jdenticon.PngExtensions.SaveAsPng (Jdenticon.Identicon icon) [0x00000] in <ab564dc515b94c289a2d06cfad69bf6e>:0 
  at Celeste.AreaComplete.InitAreaCompleteInfoForEverest () [0x00044] in <f67873230255473bbf7a49703e3fe7a1>:0 
  at Celeste.AreaComplete.Begin () [0x00006] in <f67873230255473bbf7a49703e3fe7a1>:0 
  at Monocle.Engine.Update (Microsoft.Xna.Framework.GameTime gameTime) [0x00257] in <f67873230255473bbf7a49703e3fe7a1>:0 
  at Celeste.Celeste.Update (Microsoft.Xna.Framework.GameTime gameTime) [0x00030] in <f67873230255473bbf7a49703e3fe7a1>:0 
  at Microsoft.Xna.Framework.Game.Tick () [0x000ef] in <c994aff8e9de4ec0be68f9560d5a1f85>:0 
  at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop (Microsoft.Xna.Framework.Game game) [0x006a1] in <c994aff8e9de4ec0be68f9560d5a1f85>:0 
  at Microsoft.Xna.Framework.Game.Run () [0x0002c] in <c994aff8e9de4ec0be68f9560d5a1f85>:0 
  at Monocle.Engine.RunWithLogging () [0x00000] in <f67873230255473bbf7a49703e3fe7a1>:0 
```

**Closed** 2020-04-04 12:06 UTC
